### ISSUE TITLE
FileNotFoundError: [WinError 2] 

### ISSUE THREAD

**Issue by Max1897** [PredWanTE/DOTE#1]
When computing optimum for the GEANT data. A **FileNotFoundError: [WinError 2]**  error was raised.
I think I have followed steps in Readme. The following are the details.

INFO: Reset logger
INFO: Logging to <built-in function dir>
[+] Populating TMS.
100%|██████████| 2016/2016 [00:00<00:00, 6740.25it/s]
[+] Populating TMS.
100%|██████████| 2016/2016 [00:00<00:00, 6728.46it/s]
[+] Populating TMS.
100%|██████████| 2016/2016 [00:00<00:00, 7113.89it/s]
[+] Populating TMS.
100%|██████████| 2016/2016 [00:00<00:00, 6739.96it/s]
100%|██████████| 16/16 [00:00<?, ?it/s]
[+] Populating TMS.
[+] Populating TMS.
100%|██████████| 2016/2016 [00:00<00:00, 6747.10it/s]
  0%|          | 0/677 [00:00<?, ?it/s][+] Populating TMS.
100%|██████████| 677/677 [00:00<00:00, 7186.68it/s]
  0%|          | 0/5 [00:00<?, ?it/s]
[+] Processing training data...

100%|██████████| 5/5 [00:00<00:00,  5.12it/s]
100%|██████████| 2/2 [00:00<00:00,  6.37it/s]
[+] Finished processing training data.

[+] Start training...

100%|██████████| 484/484 [00:01<00:00, 246.82it/s]
100%|██████████| 484/484 [00:00<00:00, 30969.38it/s]
  0%|          | 0/484 [00:00<?, ?it/s]
[+] Finished training.
100%|██████████| 484/484 [00:00<00:00, 1618.54it/s]
INFO: Reset logger
INFO: Logging to <built-in function dir>
  0%|          | 0/2693 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "../../ml/sl_algos/evaluate.py", line 72, in <module>
    main(sys.argv[1:])
  File "../../ml/sl_algos/evaluate.py", line 38, in main
    SLU.compute_cplex_res(props) 
  File "C:\D Drive\Tandon\Spring2023\Network\project\DOTE\networking_envs\ml\sl_algos\utils.py", line 272, in compute_cplex_res
    ress, ress_all = get_all_cplex_res(props, y_hat, y)
  File "C:\D Drive\Tandon\Spring2023\Network\project\DOTE\networking_envs\ml\sl_algos\utils.py", line 253, in get_all_cplex_res
    res_str = DU.get_opt_cplex(props, tm * factor_units, next_tm * factor_units, opt_function=props.opt_function,
  File "C:\D Drive\Tandon\Spring2023\Network\project\DOTE\networking_envs\data_gen\utils.py", line 96, in get_opt_cplex
    res = jar_gurobi_wrapper(props, props.gurobi_path, args_java)
  File "C:\D Drive\Tandon\Spring2023\Network\project\DOTE\networking_envs\data_gen\utils.py", line 37, in jar_gurobi_wrapper
    process = Popen(['java'] + ['-jar'] + [args[0]] + ['param.tmp'], stdout=PIPE, stderr=PIPE)
  File "C:\Users\xiong\anaconda3\envs\Network_project\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xiong\anaconda3\envs\Network_project\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
File "C:/D Drive/Tandon/Spring2023/Network/project/DOTE/networking_envs/data/GEANT/compute_opts.py", line 19, in <module>
    subprocess.run(['python', '../../ml/sl_algos/evaluate.py', '--ecmp_topo', topology_name, '--hist_len', '0', '--sl_type', 'eval', '--compute_opts', '--opts_dir', test_opts_dir], check=True)
  File "C:\Users\xiong\anaconda3\envs\Network_project\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '../../ml/sl_algos/evaluate.py', '--ecmp_topo', 'GEANT', '--hist_len', '0', '--sl_type', 'eval', '--compute_opts', '--opts_dir', 'opts_test']' returned non-zero exit status 1.

**Comment by Max1897** [comment]
I solved this issue by adding (shell  = True) in a popen call
